"""add tutor is_registered

Revision ID: 227e1c4037d6
Revises: ce8bfeda06c7
Create Date: 2026-05-10 20:39:27.327061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227e1c4037d6'
down_revision: Union[str, Sequence[str], None] = 'ce8bfeda06c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'tutors',
        sa.Column('is_registered', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Backfill: anyone who already completed onboarding before this gate existed
    # is implicitly registered.
    op.execute("UPDATE tutors SET is_registered = true WHERE onboarding_status = 'info_collected'")
    # Drop the server_default — Python-side default takes over for new rows.
    op.alter_column('tutors', 'is_registered', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'is_registered')
    # ### end Alembic commands ###
